class Avengers {
  final int id;
  final String name;
  final String description;
  final String avengerImage;

  Avengers(this.id,
      {required this.name,
      required this.description,
      required this.avengerImage});
}

List<Avengers> avengersList = [
  Avengers(1,
      name: "Captain\nAmerica",
      description:
          'Captain America is a superhero appearing in American comic books published by Marvel Comics. Created by cartoonists Joe Simon and Jack Kirby, the character first appeared in Captain America Comics #1 (cover dated March 1941) from Timely Comics, a predecessor of Marvel Comics. Captain America was designed as a patriotic supersoldier who often fought the Axis powers of World War II and was Timely Comics\' most popular character during the wartime period. The popularity of superheroes waned following the war, and the Captain America comic book was discontinued in 1950, with a short-lived revival in 1953. Since Marvel Comics revived the character in 1964, Captain America has remained in publication.The character wears a costume bearing an American flag motif, and he utilizes a nearly-indestructible shield that he throws as a projectile. Captain America is the alter ego of Steve Rogers, a frail young artist enhanced to the peak of human perfection by an experimental "super-soldier serum" after joining the military to aid the United States government\'s efforts in World War II. Near the end of the war, he was trapped in ice and survived in suspended animation until he was revived in modern times. Although Captain America often struggles to maintain his ideals as a man out of his time, he remains a highly respected figure both with the American public and in the superhero community, which includes becoming the long-time leader of the Avengers.Captain America was the first Marvel Comics character to appear in media outside comics with the release of the 1944 movie serial, Captain America. Since then, the character has been featured in other films and television series. In the Marvel Cinematic Universe, Steve Rogers was portrayed by Chris Evans. Captain America was ranked sixth on IGN\'s "Top 100 Comic Book Heroes of All Time" in 2011, second in their list of "The Top 50 Avengers" in 2012, and second in their "Top 25 best Marvel superheroes" list in 2014.',
      avengerImage: "asset/images/capt_america.png"),
  Avengers(2,
      name: "Iron\nMan",
      description:
          'Iron Man is a superhero appearing in American comic books published by Marvel Comics. The character was co-created by writer and editor Stan Lee, developed by scripter Larry Lieber, and designed by artists Don Heck and Jack Kirby. The character made his first appearance in Tales of Suspense #39 (cover dated March 1963), and received his own title in Iron Man #1 (May 1968). Also in 1963, the character founded the Avengers alongside Thor, Ant-Man, Wasp and the Hulk. A wealthy American business magnate, playboy, philanthropist, inventor and ingenious scientist, Anthony Edward Stark suffers a severe chest injury during a kidnapping. When his captors attempt to force him to build a weapon of mass destruction, he instead creates a mechanized suit of armor to save his life and escape captivity. Later, Stark develops his suit, adding weapons and other technological devices he designed through his company, Stark Industries. He uses the suit and successive versions to protect the world as Iron Man. Although at first cncealing his true identity, Stark eventually publicly reveals himself to be Iron Man.Initially, Iron Man was a vehicle for Stan Lee to explore Cold War themes, particularly the role of American technology and industry in the fight against communism. Subsequent re-imaginings of Iron Man have transitioned from Cold War motifs to contemporary matters of the time. Throughout most of the character\'s publication history, Iron Man has been a founding member of the superhero team the Avengers and has been featured in several incarnations of his own various comic book series. Iron Man has been adapted for several animated television shows and films. In the Marvel Cinematic Universe, Tony Stark was portrayed by Robert Downey Jr. in the films Iron Man (2008), The Incredible Hulk (2008), Iron Man 2 (2010), The Avengers (2012), Iron Man 3 (2013), Avengers: Age of Ultron (2015), Captain America: Civil War (2016), Spider-Man: Homecoming (2017), Avengers: Infinity War (2018), and Avengers: Endgame (2019), while Mick Wingertvoiced the character in the animated series What If...? (2021).Iron Man was ranked 12th on IGN\'s "Top 100 Comic Book Heroes" in 2011 and third in their list of "The Top 50 Avengers" in 2012.',
      avengerImage: "asset/images/iron_man.png"),
  Avengers(3,
      name: "Thor",
      description:
          'Thor Odinson, or simply Thor, is a fictional character appearing in American comic books published by Marvel Comics. The character is based on the Norse deity of the same name, the Asgardian god of thunder whose enchanted hammer Mjolnir enables him to fly and manipulate weather, among his other superhuman attributes. A founding member of the superhero team the Avengers, Thor has a host of supporting characters and enemies.Debuting in the Silver Age of Comic Books, the character first appeared in Journey into Mystery #83 (August 1962) and was created by artist Jack Kirby, writer Stan Lee, and scripter Larry Lieber. The character has starred in several ongoing series and limited series, and appears in all volumes of the Avengers series. The character has been used in Marvel Comics merchandise, animated television series, movies, video games, clothing and toys.Chris Hemsworth portrays the character in several Marvel Cinematic Universe films: Thor (2011), The Avengers (2012), Thor: The Dark World (2013), Avengers: Age of Ultron (2015), Doctor Strange (2016, cameo), Thor: Ragnarok (2017), Avengers: Infinity War (2018), Avengers: Endgame (2019), and the upcoming Thor: Love and Thunder (2022). Alternative versions of the character appear in the Disney+ series What If...? (2021).Thor placed 14th on IGN\'s list of "Top 100 Comic Book Heroes of All Time" in 2011, and first in their list of "The Top 50 Avengers" in 2012. ',
      avengerImage: "asset/images/thor.png")
];
